// Generated by gencpp from file billing/inc_invResponse.msg
// DO NOT EDIT!


#ifndef BILLING_MESSAGE_INC_INVRESPONSE_H
#define BILLING_MESSAGE_INC_INVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace billing
{
template <class ContainerAllocator>
struct inc_invResponse_
{
  typedef inc_invResponse_<ContainerAllocator> Type;

  inc_invResponse_()
    : success()  {
    }
  inc_invResponse_(const ContainerAllocator& _alloc)
    : success(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::billing::inc_invResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billing::inc_invResponse_<ContainerAllocator> const> ConstPtr;

}; // struct inc_invResponse_

typedef ::billing::inc_invResponse_<std::allocator<void> > inc_invResponse;

typedef boost::shared_ptr< ::billing::inc_invResponse > inc_invResponsePtr;
typedef boost::shared_ptr< ::billing::inc_invResponse const> inc_invResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::billing::inc_invResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::billing::inc_invResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::billing::inc_invResponse_<ContainerAllocator1> & lhs, const ::billing::inc_invResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::billing::inc_invResponse_<ContainerAllocator1> & lhs, const ::billing::inc_invResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace billing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::billing::inc_invResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::billing::inc_invResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::billing::inc_invResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::billing::inc_invResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::billing::inc_invResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::billing::inc_invResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::billing::inc_invResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6563811f75f3715f19a981f2cc0a3560";
  }

  static const char* value(const ::billing::inc_invResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6563811f75f3715fULL;
  static const uint64_t static_value2 = 0x19a981f2cc0a3560ULL;
};

template<class ContainerAllocator>
struct DataType< ::billing::inc_invResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "billing/inc_invResponse";
  }

  static const char* value(const ::billing::inc_invResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::billing::inc_invResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string success\n"
"\n"
;
  }

  static const char* value(const ::billing::inc_invResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::billing::inc_invResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inc_invResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billing::inc_invResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::billing::inc_invResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BILLING_MESSAGE_INC_INVRESPONSE_H
