// Generated by gencpp from file billing/inc_inv.msg
// DO NOT EDIT!


#ifndef BILLING_MESSAGE_INC_INV_H
#define BILLING_MESSAGE_INC_INV_H

#include <ros/service_traits.h>


#include <billing/inc_invRequest.h>
#include <billing/inc_invResponse.h>


namespace billing
{

struct inc_inv
{

typedef inc_invRequest Request;
typedef inc_invResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct inc_inv
} // namespace billing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::billing::inc_inv > {
  static const char* value()
  {
    return "31f8c6a2c4eb0a57e12824b70548dc9d";
  }

  static const char* value(const ::billing::inc_inv&) { return value(); }
};

template<>
struct DataType< ::billing::inc_inv > {
  static const char* value()
  {
    return "billing/inc_inv";
  }

  static const char* value(const ::billing::inc_inv&) { return value(); }
};


// service_traits::MD5Sum< ::billing::inc_invRequest> should match
// service_traits::MD5Sum< ::billing::inc_inv >
template<>
struct MD5Sum< ::billing::inc_invRequest>
{
  static const char* value()
  {
    return MD5Sum< ::billing::inc_inv >::value();
  }
  static const char* value(const ::billing::inc_invRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::billing::inc_invRequest> should match
// service_traits::DataType< ::billing::inc_inv >
template<>
struct DataType< ::billing::inc_invRequest>
{
  static const char* value()
  {
    return DataType< ::billing::inc_inv >::value();
  }
  static const char* value(const ::billing::inc_invRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::billing::inc_invResponse> should match
// service_traits::MD5Sum< ::billing::inc_inv >
template<>
struct MD5Sum< ::billing::inc_invResponse>
{
  static const char* value()
  {
    return MD5Sum< ::billing::inc_inv >::value();
  }
  static const char* value(const ::billing::inc_invResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::billing::inc_invResponse> should match
// service_traits::DataType< ::billing::inc_inv >
template<>
struct DataType< ::billing::inc_invResponse>
{
  static const char* value()
  {
    return DataType< ::billing::inc_inv >::value();
  }
  static const char* value(const ::billing::inc_invResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BILLING_MESSAGE_INC_INV_H
